export const USER_PROFILE: string;
export const USER_ACCOUNT: string;
export const USER_DEVICE: string;
export const COMPANY: string;
export const BUSINESS_SECTOR: string;
export const BUSINESS_INDUSTRY: string;
export const USER_CREATED_LIST: string;
export const POST: string;
export const IDEA: string;
