module.exports = {
  getPostByID: jest.fn(),
  getIdeaByID: jest.fn(),
  getPostsByAuthor: jest.fn(),
  getIdeasByAuthor: jest.fn(),
  getReplies: jest.fn(),
  getReactions: jest.fn(),
  createPost: jest.fn(),
  updatePost: jest.fn(),
  deletePost: jest.fn(),
  createIdea: jest.fn(),
  updateIdea: jest.fn(),
  deleteIdea: jest.fn(),
  createReaction: jest.fn(),
  deleteReaction: jest.fn(),
  reportContent: jest.fn(),
  loadReactionStatus: jest.fn(),
  loadReactionCount: jest.fn(),
  loadReplyCount: jest.fn(),
  loadReplyStatus: jest.fn(),
};
